server:
  port: ${PORT:8080}
  error.include-message: always
  servlet:
    contextPath: /fashion

spring:
  application:
    name: fashion-java-backend
  jpa:
    hibernate:
      ddl-auto: create-drop